name: cognition_package
description: A Flutter framework for cognitive testing. Contains 14 pre-defined cognitive tests and an API for creating your own.
version: 1.5.0
homepage: https://github.com/cph-cachet/cognition_package

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carp_serializable: ^1.1.0
  research_package: ^1.3.2
  json_annotation: ^4.8.1
  just_audio: ^0.9.34
  reorderables: ^0.6.0

dev_dependencies:
  flutter_lints: any
  test: any
  build_runner: any
  json_serializable: any

# Overriding research package to use the local copy
# Remove this before release of package
# dependency_overrides:
#   research_package:
#     path: ../research.package/

# auto generate json code (.g files) with:
#   flutter pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/
    - assets/sounds/
